import { z } from 'zod'
import { ANIMATION_STATES, MOTIONS, type AnimationState } from './states'

/**
 * THE CONTRACT between the design workstream and the app.
 *
 * Everything the engine knows about a character comes through this schema and
 * nothing else. If a change to the art requires a change to app code, the
 * boundary has leaked and the fix belongs here, not in a renderer special-case.
 *
 * manifest.json is GENERATED by tools/pack-sprites.py from character.json.
 * This schema validates the generated artefact at load time so a bad or
 * hand-edited manifest fails loudly with a path, rather than rendering a
 * silently broken sprite.
 */

export const HitBoxSchema = z.object({
  x: z.number().min(0).max(1),
  y: z.number().min(0).max(1),
  w: z.number().gt(0).max(1),
  h: z.number().gt(0).max(1),
})

export const StateSchema = z.object({
  atlas: z.string().min(1),
  frameCount: z.int().positive(),
  sequence: z.array(z.int().nonnegative()).min(1),
  fps: z.number().positive().max(60),
  motion: z.enum(MOTIONS),
  hitBox: HitBoxSchema,
})

export const ManifestSchema = z
  .object({
    name: z
      .string()
      .min(1)
      .regex(/^[a-z0-9][a-z0-9-]*$/, 'must be lowercase kebab-case'),
    displayName: z.string().min(1),
    author: z.string().nullish(),
    version: z.literal(1),
    generated: z.boolean().optional(),
    canvas: z.object({
      width: z.int().positive(),
      height: z.int().positive(),
    }),
    // Every frame is normalised onto one canvas and anchored at bottom-centre,
    // so switching states never moves the character's contact point.
    anchor: z.literal('bottom-center'),
    states: z.record(z.string(), StateSchema),
  })
  .superRefine((m, ctx) => {
    for (const required of ANIMATION_STATES) {
      if (!m.states[required]) {
        ctx.addIssue({
          code: 'custom',
          path: ['states', required],
          message: `character "${m.name}" is missing required state "${required}"`,
        })
      }
    }
    for (const [name, s] of Object.entries(m.states)) {
      for (const [i, frame] of s.sequence.entries()) {
        if (frame >= s.frameCount) {
          ctx.addIssue({
            code: 'custom',
            path: ['states', name, 'sequence', i],
            message: `sequence references frame ${frame} but atlas has ${s.frameCount}`,
          })
        }
      }
    }
  })

export type Manifest = z.infer<typeof ManifestSchema>
export type StateSpec = z.infer<typeof StateSchema>

export function stateSpec(m: Manifest, state: AnimationState): StateSpec {
  // Presence of every AnimationState is guaranteed by the schema refinement.
  return m.states[state]!
}

/** Width / height of the shared canvas — the overlay window's fixed ratio. */
export function aspectRatio(m: Manifest): number {
  return m.canvas.width / m.canvas.height
}
